### ISSUE TITLE
When I run make run, I can't send anything，It looks like I can't link locally ollama

### ISSUE THREAD

**Issue by sweet957** [OpenHands/OpenHands#1019]
#### Describe the bug

When I run make run, it looks like it didn't start successfully
#### Setup and configuration
**Current version**:

```bash
```

**My config.toml and environment vars** (be sure to redact API keys):
```toml
LLM_API_KEY="ollama"

LLM_MODEL="ollama/codellama:7b-instruct-fp16"

LLM_EMBEDDING_MODEL="local"

LLM_BASE_URL="http://localhost:11434"

WORKSPACE_DIR="./workspace"
```

**My model and agent** (you can see these settings in the UI):
* Model:anyscale/meta-llama/Llama-2-13b-chat-hf
* Agent:CodeActAgent

**Commands I ran to install and run OpenDevin**:
```
make build
make run
```

**Steps to Reproduce**:
1.make run
2.
3.

**Logs, error messages, and screenshots**:

#### Additional Context
1.When I run make run
![image](https://github.com/OpenDevin/OpenDevin/assets/62953888/d92964a6-7bd8-4a70-bfff-e7728b0f35ed)

2.When I found that I could open the screen but couldn't send anything, I refreshed the screen
![image](https://github.com/OpenDevin/OpenDevin/assets/62953888/cf5b1bf6-2db0-4c41-b0c8-891c55f97f0b)
![image](https://github.com/OpenDevin/OpenDevin/assets/62953888/786d6f9a-e100-4ec0-8e85-3f58ff1f9a81)
